### ISSUE TITLE
(Feature Request) Github Action

### ISSUE THREAD

**Issue by ppeters0502** [devops-kung-fu/bomber#102]
I saw in the documentation there were some advanced usage tips for generating an SBOM with Syft and scanning that with bomber within 1 command, for CI/CD workflows. With this in mind, has there been any thought to possibly making a github action with this project?

**Comment by djschleen** [comment]
Absolutely! Thanks for creating the feature.... we'll get this going.

**Comment by djschleen** [comment]
@garethr FYI

**Comment by djschleen** [comment]
[https://github.com/devops-kung-fu/bomber-action](https://github.com/devops-kung-fu/bomber-action)

Development is underway

**Comment by ppeters0502** [comment]
Awesome, thanks! If you guys are open to new contributors I can fork it and see if I can get a basic action up and running?

**Comment by ppeters0502** [comment]
@djschleen I submitted a pull request to get a basic composite action up and running. Got it successfully working on a separate repository of mine, the action uses the anchor/sbom-action github action, to generate an SBOM, and then runs a shell script to download, install and run bomber against said SBOM.
If you guys already have a different direction you want to take that action, I can close that PR no problem! Just thought I'd try to get something started!

**Comment by djschleen** [comment]
@ppeters0502 you rock! Thanks for getting that in. I'm going to close this and we'll take the convo over to [https://github.com/devops-kung-fu/bomber-action](https://github.com/devops-kung-fu/bomber-action)
