### ISSUE TITLE
POM/Maven scanning capability

### ISSUE THREAD

**Issue by nhopkins19** [devops-kung-fu/bomber#112]
Could we potentially add the ability for Bomber to scan pom(maven) files, and if so, what would be needed to accomplish this?

Maybe we could create a wrapper for his Maven POM parser:

 https://github.com/raux/PomWalker

**Comment by nhopkins19** [comment]
@djschleen Let me know what you think

**Comment by djschleen** [comment]
Hey @nhopkins19 - use Syft or another SBOM generator to create the SBOM, and then bomber will scan it for vulnerabilities.
