### ISSUE TITLE
the 0.4.1 version in release will show 0.4.0 and  show "open : no such file or directory" error

### ISSUE THREAD

**Issue by erichsu0937** [devops-kung-fu/bomber#140]
the 0.4.1 version will show 0.4.0
![image](https://user-images.githubusercontent.com/25108880/222685960-3cada720-7547-48af-8cb6-948756e6e93f.png)
 
and 

there is an error but the real 0.4.0 work fine
![image](https://user-images.githubusercontent.com/25108880/222686309-55f42104-805f-4990-a57d-44ddd9d380c9.png)

**Comment by djschleen** [comment]
Sorry about this one... this was a problem where it was trying to load the ignore file from an empty directory. This is going to be fixed in 0.4.2 which I'm just about to push.
