### ISSUE TITLE
error retrieving vulnerability data (400 Bad Request)

### ISSUE THREAD

**Issue by snowuyl** [devops-kung-fu/bomber#152]
bomber scan ./sbom.json 

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.4.2

■ Ecosystems detected: pypi
■ Scanning 51 packages for vulnerabilities...
■ Vulnerability Provider: OSV Vulnerability Database (https://osv.dev) 

■ error retrieving vulnerability data (400 Bad Request)

**Comment by djschleen** [comment]
We'll take a look. Thank you for providing the SBOM for testing!

**Comment by djschleen** [comment]
In your SBOM you have a package that points to a local wheel, which is going to cause problems with the OSV provider.

```023/04/13 12:40:35 Purl: pkg:pypi/file:///home/amenginetek/amhrv-1.7.0-py3-none-any.whl
2023/04/13 12:40:35 { {  pkg:pypi/file:///home/amenginetek/amhrv-1.7.0-py3-none-any.whl}}```

We'll need to catch this, and put a good error message out.
