### ISSUE TITLE
error retrieving vulnerability data (400 Bad Request)

### ISSUE THREAD

**Issue by AJIOXA** [devops-kung-fu/bomber#174]
no errors due to installation steps, no errors due to downloading cve via other free scan tools
however i see following error due to trying of execution bomber scanning in docker, on macos system and in gitlab-ci steps
few days ago all was good, no error due to analyze same bom file generated via CycloneDX

![bomber](https://github.com/devops-kung-fu/bomber/assets/70650208/3c20069a-97ed-40fa-9474-07e835b2c9bf)

**Comment by ZheSun88** [comment]
we are having the same issue and it seems this started from 3 days ago.

**Comment by mdfad-tech** [comment]
Likewise, still facing this issue

**Comment by skinny-b** [comment]
Same, I found that the request being sent to osv.dev can look like this:
```
{
    "version": "",
    "package":{
        "purl": "pkg:cargo/aho-corasick@0.7.20"
    }
}
```
The result of the 400 is:
```
{
    "code": 3,
    "message": "version specified in params and purl query"
}
```

**Comment by AJIOXA** [comment]
> Same, I found that the request being sent to osv.dev can look like this:
> 
> ```
> {
>     "version": "",
>     "package":{
>         "purl": "pkg:cargo/aho-corasick@0.7.20"
>     }
> }
> ```
> 
> The result of the 400 is:
> 
> ```
> {
>     "code": 3,
>     "message": "version specified in params and purl query"
> }
> ```
> 
> if I remove the version element and just send package I get a 200 for what I'm checking.

maybe you have any idea  how to realise this fix in gitlab-ci way or your way of usage not connected with pipelines?
Thank you in advance for the answer!

**Comment by skinny-b** [comment]
I was making the curl request to the server manually after I saw how to get a 200, I modified bomber in my local git to output the data being sent, saw the version being passed like that and tried with curl and saw the response above. From what I can tell is in `providers/osv/osv.go` commenting out the Version in the Query struct worked:
```
...
type Query struct {
    //Version string       `json:"version"`
...
```

I'm not sure this is a solid fix though as I'm not really familiar with where the struct is being used everywhere. I think the osv.dev server updated something that doesn't allow it to pass that way anymore, but I couldn't find a changelog for it, unless they're always deploying the latest code from their github and not the latest release(Saw marked in Feb).

**Comment by djschleen** [comment]
I'll take a look at this one...

**Comment by djschleen** [comment]
Okay... good news is that I have a fix coming. OSV must have changed a bit of the API as if a Purl is specified, name and version shouldn't be set. Makes sense. 

There's some breaking tests for Snyk that I'll be fixing, and once the tests work out, I'll get it released.
