### ISSUE TITLE
False version display 0.4.5 bomber

### ISSUE THREAD

**Issue by AJIOXA** [devops-kung-fu/bomber#176]
![bomberIssues](https://github.com/devops-kung-fu/bomber/assets/70650208/e1d59662-5222-4d63-ac73-31c8b9bf3c70)
I have downloaded new version of bomber 0.4.5, however bomber displays current version as 0.4.4
also not sure why, but currently bomber generate report and the exit with code 1
![bomber2](https://github.com/devops-kung-fu/bomber/assets/70650208/779c9412-8678-417a-9876-be8471cdb844)
![bomber3](https://github.com/devops-kung-fu/bomber/assets/70650208/a2a2174a-ba0b-4dcb-a4ec-de09b025d758)
as far as i understood, exit code 1 is just because of critical issues in report of bomber, but is it possible to set by myself the number of issues which will cause exit code 1?
Thank you in advance!

**Comment by AJIOXA** [comment]
Founded flag --fail
just not displays in --help menu

**Comment by djschleen** [comment]
I'll take care of that and bump the version

**Comment by ZheSun88** [comment]
we have run the bomber 0.4.5 (sceenshown version 0.4.4 like it mentioned above)

we got this summary. 
```
"summary": {
		"Unspecified": 0,
		"Low": 0,
		"Moderate": 0,
		"High": 0,
		"Critical": 0
	}
```

then the exit code returns `10`, should it return `0` instead?

**Comment by djschleen** [comment]
@ZheSun88 we have a fix for it coming out today to address the exit code logic, and have updated the README.md to explain what the --severity and --exitcode flag are.
