### ISSUE TITLE
Doesn't work with CycloneDX version 1.5

### ISSUE THREAD

**Issue by anthonyharrison** [devops-kung-fu/bomber#182]
Scanning a CycloneDX JSON SBOM (version 1.5) results in failure

2023/11/10 09:19:33 Start

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.4.6

2023/11/10 09:19:34 Reading: cvebintool.json
2023/11/10 09:19:34 Detected CycloneDX JSON
■ json: cannot unmarshal object into Go struct field Metadata.metadata.tools of type []cyclonedx.Tool

**Comment by djschleen** [comment]
@anthonyharrison thanks for reporting! ```bomber``` uses https://github.com/CycloneDX/cyclonedx-go to process go files. At this time, the only version that supports 1.5 is cyclonedx-go release v0.8.0 - and unfortunately that hasn't been released yet.

The latest release that ```bomber``` uses is 0.7.2 which supports the partial 1.5 spec (per https://github.com/CycloneDX/cyclonedx-go/releases) 

```bomber``` should automatically update itself once the 0.8.0 lib is out.
