### ISSUE TITLE
Extract removeDuplicates to DKFM Common

### ISSUE THREAD

**Issue by djschleen** [devops-kung-fu/bomber#19]
The removeDuplicates function is handy and we can use it elsewhere in DKFM. Extract it from here, move it to DKFM Common (needs to be uppercased there), and wire bomber to use the new common version

**Comment by nhopkins19** [comment]
In the process of working on this one. Testing completed successfully, now I need to tie in Bomber to point to Common for this slice

**Comment by djschleen** [comment]
Cool! We need to add the release.yml file in from DKFM strictly and automate the release.
