### ISSUE TITLE
bomber doesn't detect packages

### ISSUE THREAD

**Issue by davidmthomsen** [devops-kung-fu/bomber#193]
When using bomber to scan OWASPs juice-shop it doesn't pick up anything.

> bomber scan ~/tools/SBOMVisor/bom.json

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.4.8

A newer version of bomber is available ()

**Comment by djschleen** [comment]
Hey @davidmthomsen can you attach the SBOM that you are scanning for Juiceshop or is it the one in Bomber's _TESTDATA_ folder?

**Comment by djschleen** [comment]
Can't reproduce.
