### ISSUE TITLE
error retrieving vulnerability data (400 Bad Request)

### ISSUE THREAD

**Issue by ArwynFr** [devops-kung-fu/bomber#212]
I'm writing a SBOM files via Syft then merge them using cyclonedx-cli merge.
The resulting file works fine with OSV but fails with ossindex when using bomber 0.4.8:

![image](https://github.com/devops-kung-fu/bomber/assets/10365998/c9cf0ea9-2747-4e98-ab20-40f1134dbfdd)

[sbom.json](https://github.com/devops-kung-fu/bomber/files/14793265/sbom.json)

Also I think that bomber should not halt the process when an error occurs.
Even a partial scan has value ; perhaps list the unscanned components in the output.

**Comment by djschleen** [comment]
@ArwynFr - taking a look...

**Comment by djschleen** [comment]
@ArwynFr that SBOM has a ton of invalid Purls in it... 
<img width="615" alt="image" src="https://github.com/user-attachments/assets/353a005e-5a74-421b-a32b-97e6f152dbd2">

I'm writing code to try to cleanse the purls.

**Comment by djschleen** [comment]
More info:

<img width="515" alt="image" src="https://github.com/user-attachments/assets/696c2266-a2c9-4cd5-af5f-8e3962e5d27d">

Only #16 in this screenshot is valid

**Comment by djschleen** [comment]
This will be better in 0.5.0 with the following info:

* Code has been added to ensure that PURLs are as _clean as they can be_
* OSV is fine with bad PURLS and returns nothing. OSSINDEX will return an error code (now displayed when the debug flag is set to true), but WILL IGNORE THE FULL CONTENTS OF THAT SPECIFIC BATCH and continue processing. OSSINDEX allows for 128 purls to be passed at a time. If an error gets through, that whole batch is ignored in the output. See the disclaimer at the end of the bomber STDOUT message

I'm not sure what tool created the SBOM provided in the ticket, or if it was a copy paste problem, but the text in there does bind properly to a schema, but Sonatype will error on the bad purl.
