### ISSUE TITLE
Make Snyk API URL configurable

### ISSUE THREAD

**Issue by moxli** [devops-kung-fu/bomber#215]
I am trying to use bomber with Snyk and get the following error:

`/ Fetching vulnerability data from snykΓûá could not infer userΓÇÖs Snyk organization: unable to retrieve org ID (status: 401 Unauthorized)`

This is due to the fact that Snyk provides regional hosting in the EU and Australia with each region having their own API endpoints.
In this case I am using an API token for an EU based account.

> 
> API URLs
> Follow the docs as usual, but base URLs are:
> EU
> 
> API v1: https://api.eu.snyk.io/v1/
> REST API: https://api.eu.snyk.io/rest/
> AU
> 
> API v1: https://api.au.snyk.io/v1/
> REST API: https://api.au.snyk.io/rest/
> 

Source: https://docs.snyk.io/working-with-snyk/regional-hosting-and-data-residency#api-urls

**Comment by mcombuechen** [comment]
Just opened a PR for this here: #268
