### ISSUE TITLE
Bomber reporting OSV vulnerabilities on package versions that aren't in SBOM

### ISSUE THREAD

**Issue by ppeters0502** [devops-kung-fu/bomber#223]
Hello there,
We use bomber pretty extensively when reviewing open source packages and other software that are in my company's environment. I was reviewing the open source package [eslint](https://github.com/eslint/eslint) downloaded the SPDX SBOM from GitHub and ran a Bomber scan of that SBOM. The Bomber report displayed several vulnerabilities, including 5 Critical vulnerabilities that I started reviewing. One of these vulnerabilities was tied to the dependency eslint-scope, but is specific to version 3.7.2, with a patch deployed in version 3.7.3.
![image](https://github.com/devops-kung-fu/bomber/assets/6621379/659a21b7-63cf-4f9d-afb6-b80c38dd4ef9)

 the version of eslint-scope in the SBOM, and listed in the package.json file of this project is 8.0.1 though, and I'm not really sure why this vulnerability still came up for this dependency.
![image](https://github.com/devops-kung-fu/bomber/assets/6621379/256b6bbd-4c68-4613-82a4-a78b13ab6e49)
 
Are package versions checked when bomber gets an OSV or other vulnerability DB result back?

**Comment by djschleen** [comment]
We'll take a look!

**Comment by ppeters0502** [comment]
On cases where a package version isn't listed in the SBOM, I agree with still showing the vulnerability in the report, could there maybe be an update to the report where it marks that "the package version could not be determined" or something similar to that effect?

**Comment by djschleen** [comment]
This one is interesting. Which providers are you using @ppeters0502 @ivanb-blip ? OSV is a bit strange with passing package versions, OSSINDEX should be tighter.

**Comment by djschleen** [comment]
@ppeters0502 and @ivanb-blip I managed to run through this and the results that come back are expected. In your SBPM's you'll see that the reference locator does not contain a version ```pkg: npm/eslint-scope``` instead of ```pkg:npm/eslint-scope:X.X.X``` . Because of this, bomber will just echo back the result from OSV.  See https://osv.dev/vulnerability/GHSA-2mqj-m65w-jghx and https://osv.dev/vulnerability/GHSA-hxxf-q3w9-4xgw
