### ISSUE TITLE
Shows no package shown after passing Json File.

### ISSUE THREAD

**Issue by Shweta4398** [devops-kung-fu/bomber#224]
Hello Team ,

I am new to Bomber Tool. I have extracted the SBOM from Github UI . And trying to scanning it through the tool.

It gives me the below Result though my json files has the packages

<img width="795" alt="Screenshot 2024-06-25 at 5 38 09 PM" src="https://github.com/devops-kung-fu/bomber/assets/106510489/fdf09be6-599d-4ffd-a458-ad235f73cd45">

With regards,
Shweta Singh.

**Comment by Shweta4398** [comment]
@djschleen  can you help ??

**Comment by djschleen** [comment]
Hey @Shweta4398 ! Do you have an SBOM I can use for testing?

**Comment by djschleen** [comment]
Also, if you could run with the ```debug``` flag and provide that output I'd appreciate it!  I just downloaded the SPDX from the ```Insights/Dependency Graph``` menu in Github and it found 1 vuln

**Comment by Shweta4398** [comment]
Hello @djschleen ,

I tried scanning below file to scan :- 
[marketplace-blimp_AppDirect_1b9716da59a282c2bdcbb4708897c3895076a00e.json](https://github.com/user-attachments/files/16373903/marketplace-blimp_AppDirect_1b9716da59a282c2bdcbb4708897c3895076a00e.json)

 bomber scan --debug marketplace-blimp_AppDirect_1b9716da59a282c2bdcbb4708897c3895076a00e.json --output=html
2024/07/25 15:21:03 Start

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.4.8

2024/07/25 15:21:04 Reading: marketplace-blimp_AppDirect_1b9716da59a282c2bdcbb4708897c3895076a00e.json
2024/07/25 15:21:04 Detected SPDX
■ Ecosystems detected: github,githubactions
■ Scanning 2 packages for vulnerabilities...
■ Vulnerability Provider: OSV Vulnerability Database (https://osv.dev) 

2024/07/25 15:21:04 Purl: pkg:github/AppDirect/marketplace-blimp
2024/07/25 15:21:04 {{pkg:github/AppDirect/marketplace-blimp}}
| Fetching vulnerability data from osv2024/07/25 15:21:05 OSV Response Status: 200
2024/07/25 15:21:05 Purl: pkg:githubactions/AppDirect/actions/.github/workflows/dependency-review.yml@master
2024/07/25 15:21:05 {{pkg:githubactions/AppDirect/actions/.github/workflows/dependency-review.yml@master}}
/ Fetching vulnerability data from osv2024/07/25 15:21:06 OSV Response Status: 200
2024/07/25 15:21:06 Building severity summary
2024/07/25 15:21:06 Creating results
■ Writing filename: 20240725-15-21-06-bomber-results.html
2024/07/25 15:21:06 Finished

Also , tried using the debug flag.

Thank you.

**Comment by djschleen** [comment]
Thank you for sharing the SBOM. Will take a look.

**Comment by djschleen** [comment]
Hey @Shweta4398 - turns out there are no vulnerabilities detected by either provider. Neither OSV or OSSINDEX support the github or githubactions that are specified in the SBOM you were testing. I ran the following... 
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/e58f8510-bc69-4f24-8151-bbbe4de0d210">

**Comment by Shweta4398** [comment]
Hello djschleen ,

[34m■ [0mScanning Files:
	sbom_data4.json
[31m■ [0munexpected status code: 0 

Today while scanning it gave unexpected status code . Can you check??
