### ISSUE TITLE
Test to make sure bomber works on Windows

### ISSUE THREAD

**Issue by djschleen** [devops-kung-fu/bomber#45]
All that is needed here is to create a go environment on Windows, and ensure you can build and run bomber

**Comment by nhopkins19** [comment]
![IMG_5556](https://user-images.githubusercontent.com/87438259/192340814-6347a9b3-f72b-4df4-81ce-9b8654adaa25.jpg)

![IMG_5555](https://user-images.githubusercontent.com/87438259/192340853-0d6a9c07-9cbd-4735-a1ad-9ef651f419bf.jpg)
