### ISSUE TITLE
Valid but minified CycloneDX SBOM failing to scan

### ISSUE THREAD

**Issue by garethr** [devops-kung-fu/bomber#60]
Using the following SBOM https://gist.github.com/garethr/ab5e882cd23f8e7d4578466de71cf0a9#file-compressed-json

Which is a valid CycloneDX document

```
cyclonedx validate --input-file compressed.json
BOM validated successfully.
```

Using bomber build from source, from latest head (19aa8ec38f352167b66a04d9834f8a553d9b1733)

Bomber fails to scan.

```
./bomber scan --debug compressed.json
2022/09/29 05:20:09 Start

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.3.2

2022/09/29 05:20:10 Reading: sbom.json
2022/09/29 05:20:10 WARNING: sbom.json isn't a valid SBOM
■ sbom.json is not an SBOM recognized by bomber
```

However, taking the same document and passing it through `jq` works fine.

Testing with https://gist.github.com/garethr/ab5e882cd23f8e7d4578466de71cf0a9#file-uncompressed-json 

```
./bomber scan uncompressed.json

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.3.2

■ Ecosystems detected: maven
■ Scanning 81 packages for vulnerabilities...
■ Vulnerability Provider: OSV Vulnerability Database (https://osv.dev)

/ Fetching vulnerability data from osv
```

Checking the two files using https://www.jsondiff.com/ says they are semantically the same.

Just paste the following URLs into each box:

* https://gist.githubusercontent.com/garethr/ab5e882cd23f8e7d4578466de71cf0a9/raw/23492a514c6218a50f99bf97f07adbbcd26
6546c/compressed.json
* https://gist.githubusercontent.com/garethr/ab5e882cd23f8e7d4578466de71cf0a9/raw/23492a514c6218a50f99bf97f07adbbcd266546c/uncompressed.json

I think tried the reverse. Taking the `sbom/bomber.cyclonedx.json` document from the source and minifying it with https://codebeautify.org/jsonminifier.

This results in https://gist.github.com/garethr/ab5e882cd23f8e7d4578466de71cf0a9#file-sbom_bomber-compressed-cyclonedx-json

I can confirm this then fails in Bomber.

```
bomber scan sbom/bomber.compressed.cyclonedx.json

 ██▄ ▄▀▄ █▄ ▄█ ██▄ ██▀ █▀▄
 █▄█ ▀▄▀ █ ▀ █ █▄█ █▄▄ █▀▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/bomber
Version: 0.3.2

■ sbom/bomber.compressed.cyclonedx.json is not an SBOM recognized by bomber
```

**Comment by djschleen** [comment]
I figured out what's going on here. The loadFilePurls function in ```bomloader.go``` loads the files into a slice of bytes and then searches to see if the slice contains a specific string.  Currently ```bomber``` looks for ``` []byte("\"bomFormat\": \"CycloneDX\",")``` to determine a CycloneDX file, but the minified JSON doesn't have the space after the ```:``` in the search string so doesn't match.

Resolution (and a better way of doing things) will be to implement regex searches to identify file types for unmarshalling.
