### ISSUE TITLE
feat: Add support for scanning .sbt files

### ISSUE THREAD

**Issue by nhopkins19** [devops-kung-fu/bomber#62]
Would like to add the ability to scan build.sbt files for vulnerabilities. 

Could we add a new command like "bomber convert", which would use something like syft to convert the file into CycloneDX format. And then we could run "bomber scan" on the newly created file and boom!

**Comment by djschleen** [comment]
Syft would be used separately on the source code to generate the SBOM. We just scan SBOMs for vulnerabilities with ```bomber```
