### ISSUE TITLE
Sort vulnerabilities by severity in HTML and JSON output

### ISSUE THREAD

**Issue by djschleen** [devops-kung-fu/bomber#70]
Example sorting. Can we make this generic?

func SortASC(products []entities.Product) {
	sort.Slice(products, func(i, j int) bool {
		return products[i].Price < products[j].Price
	})
}

**Comment by djschleen** [comment]
@mtverraen It is! If you want to take in on, I'd really appreciate it! You could also add a generic version if you'd like to [https://github.com/devops-kung-fu/common](https://github.com/devops-kung-fu/common) and then bring it in here.

**Comment by mtverraen** [comment]
Allright :D
