### ISSUE TITLE
Offline functionality for air-gapped environments

### ISSUE THREAD

**Issue by ataraxus** [devops-kung-fu/bomber#83]
Are there any plans to support offline functionality for air-gapped environments?

**Comment by ataraxus** [comment]
Sorry for the delayed answer. Currently we are using trivy, which has a very nice Support for airgapped environments

**Comment by djschleen** [comment]
I took a look at Trivvy but it doesn't look like it is going to be able to find the vulnerabilities for the purls bomber parses out of a SBOM. I know there are some standalone services that will match a purl to a vulnerability but I think those require regular signature updates from the public internet.

**Comment by djschleen** [comment]
Issue #98 should make this a reality.

**Comment by djschleen** [comment]
This will be covered by #98
