### ISSUE TITLE
Add EPSS scoring

### ISSUE THREAD

**Issue by AppSecConcierge** [devops-kung-fu/bomber#86]
An EPSS scoring alongside the NVD data would help contextualize the risk(s) presented in an SBOM.

**Comment by djschleen** [comment]
@AppSecConcierge We're all coded up and just working out some issues showing percentages properly in the HTML output.

**Comment by AppSecConcierge** [comment]
Thanks DJ. Amazing speed of response!

**Comment by djschleen** [comment]
<img width="647" alt="Screen Shot 2022-11-22 at 5 15 57 PM" src="https://user-images.githubusercontent.com/32048395/203449530-4f3a0cbe-7357-4489-8e9b-d83e73bb9d93.png">

**Comment by djschleen** [comment]
Released
