### ISSUE TITLE
qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by anotherbridge** [devops-kung-fu/bomber#95]
I tried to integrate bomber into a CI pipeline and got the following output when running it: 

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

I ran 
```
bomber scan sbom.json --output=json
```

The same issue appeared when specifying the output to be HTML. Yet when previously testing the tool via an SSH connection manually I did not encounter any type of issue and the report was generated for all supported types of outputs. The machine I used for testing had the same hardware available. 

Do you have any idea what's causing this issue?

**Comment by djschleen** [comment]
That's a strange one. Bomber doesn't have any UI, so I'm not sure why there is a Qt error. I'll take a look through the dependencies and see what I can come up with.

**Comment by djschleen** [comment]
@anotherbridge Which CI solution are you using? What OS?  Looks like Ubuntu running wayland?

**Comment by anotherbridge** [comment]
@djschleen I'm using Jenkins hosted on a Debian 11 machine. Further Jenkins is running the pipeline that is using bomber on an agent that is connected via SSH to the Jenkins control server. 

However, when connecting to the exact same machine from my local host and running bomber it runs without any issues.

**Comment by djschleen** [comment]
Hey @anotherbridge - I did some more digging into this and bomber doesn't have any Qt dependencies, so it may be Jenkins and how it is connecting to run bomber on the remote machine. There shouldn't be any execution difference, seeing that you can get in there directly with SSH and run it on the server itself.  

Check out Jenkins and see how it is calling bomber remotely. I found this which may help:

``` baseh
    stage("RUN BOMBER"){
        steps {
            script {
                    sh """
                    #!/bin/bash
                    sudo ssh -i /path/path/keyname.pem username@serverip << EOF
                    sudo [path to bomber]/bomber scan sbom.json --output=json //assume that sbom is available in current folder, otherwise put an explicit path there
                    exit 0
                    << EOF
                    """
                }
        }
    }
```

**Comment by anotherbridge** [comment]
@djschleen Thanks very much for the insights. Yet, this didn't have to do anything with the issue. Nevertheless I was able to fix the problem which originated from a completely different source and I shortly want to share it in case anyone else is facing this. It does not even have to anything with the implementation of the tool itself. 

The difference between the two scenarios described was that when installing bomber via a cloud agent `apt` would recognize the `.deb` file, but still choose a bomber package that was present in it's package repository over the local one. The one installed from apt, however, is an arcade game. This is also the reason why it was giving these weird dependency issues. 

Installing bomber via dpkg resolved the problem, since it would still use the file presented: 
```
dpkg -i ./bomber.deb
```
